name: Build PhyWeb

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Flatpak (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y flatpak flatpak-builder
        sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

        # UNIQUEMENT le runtime freedesktop
        sudo flatpak install -y flathub \
          org.freedesktop.Platform//23.08 \
          org.freedesktop.Sdk//23.08

        flatpak remotes

    - name: Build app
      run: npm run make
      env:
        DEBUG: '*'
        CI: true

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PhyWeb-Builds-${{ matrix.os }}
        path: out/make/**/*